title: analys-liu的博客 # 网站的标题
description: > # 网站的描述，可能会出现在搜索引擎展示结果中
  基于 jekyll 的 Github Pages 个人博客网站，技术的学习、总结、分享与提升

url: "https://analy-liu.github.io/" # 网站地址
github_repo: "https://github.com/analy-liu/analy-liu.github.io"
github_profile: "https://github.com/analy-liu" # GitHub 个人主页
user: "analy-liu" # 用于侧栏展示的名字
user_email: "analysis.liu@qq.com" # 侧栏展示的联系方式
paginate: 5 # 主页展示的博客文章数量
nick_name: "analy-liu" # 昵称
english_name: "analy-liu"

show_downloads: true
# google_analytics:
theme: jekyll-theme-leap-day